### ISSUE TITLE
Harmful site?

### ISSUE THREAD

**Issue by DudeThatsErin** [stephenou/fruitionsite#208] opened 2022-10-11 20:02 UTC
I've had fruition going on dudethatserin.com and codinghelp.site for a while.

Right now dudethatserin.com still works but something happened to codinghelp.site Edge is showing it may be a dangerous site but the URL shows it is for Notion.
![Click here to see what I mean](https://user-images.githubusercontent.com/2681022/195187388-5f21b55e-bb0e-4698-9d16-6c2aa7ddf23d.png)

Link for yourself: https://codinghelp.site/4c97396d18034520bf450b7d7485a4c4

**Comment by perogeremmer** [comment] 2022-11-09 15:36
Hey did you find the issue? I got my website also detected as phishing.

[https://tellstories.id](https://tellstories.id)

**Comment by gojomo** [comment] 2022-11-10 17:45
Duplicate of #177; see [my comment there](https://github.com/stephenou/fruitionsite/issues/177#issuecomment-1139789324). (You probably need to take this up with Google, not `fruitionsite` project.)

**Closed as completed** 2023-05-30 23:04 UTC
